### ISSUE TITLE
Bug introduced in most recent release

### ISSUE THREAD

**Issue by thisissami** [ankityadav0294/disable-facebook-news-feed#2]
Now when I click on a notification related to a post that I've created myself (e.g. somebody has commented on something that I wrote), it is hidden too. 

Here's an image of where I'd normally expect to see a post (and did yesterday):

![Screenshot from 2020-03-14 19-52-59](https://user-images.githubusercontent.com/251041/76694208-8807de80-662d-11ea-9f47-7a19e0e10836.png)

**Comment by thisissami** [comment]
I've reverted to v1.6 and my post now appears properly.

**Comment by ankityadav0294** [comment]
I have disabled the 1.7 version for now and look for  a fix. @ArtyomZorin FYI since you uploaded the fix.

**Comment by thisissami** [comment]
@ankityadav0294 thanks for the super fast response!! I didn't even notice it. It's worth noting that there is a new facebook design that I just got access to. Perhaps v1.7 is meant to address changes with that? Personally, I'm choosing not to use the new FB design because I don't like it (they give you the option to revert).

I haven't played around to see if 1.7 works with that or not - but given that facebook lets you choose one or the other.. it'll probably take a bit of work to make sure this supports both versions. 

Thanks for creating this library by the way!! I love it very much and it has made a big difference in my life. :) So many hours would have been wasted otherwise.
